            - name: ShellCheck
  # You may pin to the exact commit or the version.
  # uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38
  uses: ludeeus/action-shellcheck@2.0.0
  with:
    # A space separated list of additional filename to check
    additional_files: # optional, default is 
    # Paths to ignore when running ShellCheck
    ignore: # optional, default is 
    # Paths to ignore when running ShellCheck
    ignore_paths: # optional, default is 
    # Names to ignore when running ShellCheck
    ignore_names: # optional, default is 
    # Minimum severity of errors to consider. Options: [error, warning, info, style]
    severity: # optional, default is 
    # Run shellcheck on _all_ files at once, instead of one at a time
    check_together: # optional, default is 
    # Directory to be searched for files. Defaults to .
    scandir: # optional, default is .
    # Set to true to skip using problem-matcher
    disable_matcher: # optional, default is false
    # Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
    format: # optional, default is gcc
    # Specify a concrete version of ShellCheck to use
    version: # optional, default is stable
          
